# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProtoSchema/GameFlowData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eProtoSchema/GameFlowData.proto\x12\rtemplate_game\"\xbd\x01\n\x0cGameFlowData\x12\x34\n\x12\x63urrent_flow_state\x18\x01 \x01(\x0e\x32\x18.template_game.EFlowName\x12\x31\n\x10selected_option1\x18\x02 \x01(\x0e\x32\x17.template_game.EOption1\x12\x31\n\x10selected_option2\x18\x03 \x01(\x0e\x32\x17.template_game.EOption2\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"\xcb\x01\n\x0fGameFlowControl\x12.\n\x0ctarget_state\x18\x01 \x01(\x0e\x32\x18.template_game.EFlowName\x12\x42\n\nparameters\x18\x02 \x03(\x0b\x32..template_game.GameFlowControl.ParametersEntry\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x9c\x01\n\x12GameFlowTransition\x12,\n\nfrom_state\x18\x01 \x01(\x0e\x32\x18.template_game.EFlowName\x12*\n\x08to_state\x18\x02 \x01(\x0e\x32\x18.template_game.EFlowName\x12\x19\n\x11transition_reason\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03*a\n\tEFlowName\x12\n\n\x06\x46LOW_1\x10\x00\x12\n\n\x06\x46LOW_2\x10\x01\x12\n\n\x06\x46LOW_3\x10\x02\x12\n\n\x06\x46LOW_4\x10\x03\x12\n\n\x06\x46LOW_5\x10\x04\x12\n\n\x06\x46LOW_6\x10\x05\x12\x0c\n\x08\x46LOW_MAX\x10\x06*7\n\x08\x45Option1\x12\r\n\tOPTION1_1\x10\x00\x12\r\n\tOPTION1_2\x10\x01\x12\r\n\tOPTION1_3\x10\x02*W\n\x08\x45Option2\x12\r\n\tOPTION2_1\x10\x00\x12\r\n\tOPTION2_2\x10\x01\x12\r\n\tOPTION2_3\x10\x02\x12\r\n\tOPTION2_4\x10\x03\x12\x0f\n\x0bOPTION2_MAX\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ProtoSchema.GameFlowData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GAMEFLOWCONTROL_PARAMETERSENTRY._options = None
  _GAMEFLOWCONTROL_PARAMETERSENTRY._serialized_options = b'8\001'
  _EFLOWNAME._serialized_start=606
  _EFLOWNAME._serialized_end=703
  _EOPTION1._serialized_start=705
  _EOPTION1._serialized_end=760
  _EOPTION2._serialized_start=762
  _EOPTION2._serialized_end=849
  _GAMEFLOWDATA._serialized_start=50
  _GAMEFLOWDATA._serialized_end=239
  _GAMEFLOWCONTROL._serialized_start=242
  _GAMEFLOWCONTROL._serialized_end=445
  _GAMEFLOWCONTROL_PARAMETERSENTRY._serialized_start=396
  _GAMEFLOWCONTROL_PARAMETERSENTRY._serialized_end=445
  _GAMEFLOWTRANSITION._serialized_start=448
  _GAMEFLOWTRANSITION._serialized_end=604
# @@protoc_insertion_point(module_scope)
