# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProtoSchema/InputCommand.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eProtoSchema/InputCommand.proto\x12\rtemplate_game\"c\n\x0cInputCommand\x12+\n\nkey_inputs\x18\x01 \x03(\x0e\x32\x17.template_game.EKeyName\x12\x13\n\x0bis_key_down\x18\x02 \x01(\x08\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"n\n\x0cInputMapping\x12\x18\n\x10\x61pplicable_state\x18\x01 \x01(\x05\x12/\n\x0e\x61vailable_keys\x18\x02 \x03(\x0e\x32\x17.template_game.EKeyName\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"e\n\x12InputConfiguration\x12\x33\n\x0estate_mappings\x18\x01 \x03(\x0b\x32\x1b.template_game.InputMapping\x12\x1a\n\x12input_polling_rate\x18\x02 \x01(\x05*d\n\x08\x45KeyName\x12\t\n\x05KEY_1\x10\x00\x12\t\n\x05KEY_2\x10\x01\x12\t\n\x05KEY_3\x10\x02\x12\t\n\x05KEY_4\x10\x03\x12\t\n\x05KEY_5\x10\x04\x12\t\n\x05KEY_6\x10\x05\x12\t\n\x05KEY_7\x10\x06\x12\x0b\n\x07KEY_MAX\x10\x07\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ProtoSchema.InputCommand_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EKEYNAME._serialized_start=365
  _EKEYNAME._serialized_end=465
  _INPUTCOMMAND._serialized_start=49
  _INPUTCOMMAND._serialized_end=148
  _INPUTMAPPING._serialized_start=150
  _INPUTMAPPING._serialized_end=260
  _INPUTCONFIGURATION._serialized_start=262
  _INPUTCONFIGURATION._serialized_end=363
# @@protoc_insertion_point(module_scope)
