# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InputCommand.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12InputCommand.proto\x12\x03sr4\"^\n\x0cInputCommand\x12&\n\nkey_inputs\x18\x01 \x03(\x0e\x32\x12.sr4.EInputKeyType\x12\x13\n\x0bis_key_down\x18\x02 \x01(\x08\x12\x11\n\ttimestamp\x18\x03 \x01(\x03*\x9a\x01\n\rEInputKeyType\x12\x10\n\x0cINPUT_KEY_UP\x10\x00\x12\x12\n\x0eINPUT_KEY_DOWN\x10\x01\x12\x12\n\x0eINPUT_KEY_LEFT\x10\x02\x12\x13\n\x0fINPUT_KEY_RIGHT\x10\x03\x12\x13\n\x0fINPUT_KEY_START\x10\x04\x12\x12\n\x0eINPUT_KEY_COIN\x10\x05\x12\x11\n\rINPUT_KEY_MAX\x10\x06\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'InputCommand_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EINPUTKEYTYPE._serialized_start=124
  _EINPUTKEYTYPE._serialized_end=278
  _INPUTCOMMAND._serialized_start=27
  _INPUTCOMMAND._serialized_end=121
# @@protoc_insertion_point(module_scope)
